### ISSUE TITLE
youtube-nocookie errors

### ISSUE THREAD

**Issue by stereonom** [facebook/facebook-instant-articles-sdk-php#114]
# Steps required to reproduce the problem

insert `<iframe src="https://www.youtube-nocookie.com/embed/F0vg4HUEIyk?rel=0&amp;showinfo=0" width="640" height="360" frameborder="0" allowfullscreen="allowfullscreen"></iframe>` in the content field of wordpress

# Expected Result

```<figure class="op-social"><iframe width="640" height="360" src="https://www.youtube-nocookie.com/embed/F0vg4HUEIyk?rel=0&amp;showinfo=0"></iframe></figure>```
If youtube-nocookie isn't support just rewrite the url to `youtube.com` without the `-nocookie`.

# Actual Result

> Webview with op-social class without any supported embed type: When using op-social class on a webview, it must have a supported embed inside it e.g. Instagram, Twitter, Facebook, Youtube, etc. We didn't find any here.  

> HTML Embeds Require Valid Width: HTML Embeds require a valid integer width in order to be displayed properly.  

> HTML Embeds Require Valid Height: HTML Embeds require a valid integer height in order to be displayed properly.  

`<figure class="op-social"><iframe src="https://www.youtube-nocookie.com/embed/F0vg4HUEIyk?rel=0&amp;showinfo=0"></iframe></figure>`

**Comment by simonengelhardt** [comment]
@stereonom Thanks for flagging this. Silently rewriting the embed URL doesn't seem like the right thing to do. If someone explicitly embedded a YouTube video in the "privacy-enhanced mode", we probably shouldn't just change that to a regular embed.

Since `youtube-nocookie.com` is an officially supported form of embed, it seems it should be supported on the Facebook server side for Instant Articles and not throw those warning. Please file an issue for that here: https://developers.facebook.com/bugs/?tag_ids=121847588197534

**Comment by simonengelhardt** [comment]
The issue is tracked here: https://developers.facebook.com/bugs/237836149926788/ (requires Facebook login)
