### ISSUE TITLE
Latest Laravel requires other version of Symfony's css-selector

### ISSUE THREAD

**Issue by ronaldgj** [facebook/facebook-instant-articles-sdk-php#171]
# Steps required to reproduce the problem

1. Require version 3.* of symfony's css-selector

# Expected Result

* No errors when installing this SDK with composer in Laravel

# Actual Result

* Errors, because Laravel needs version 3.* and Facebook 2.8.

**Comment by everton-rosario** [comment]
@ronaldgj Thanks for flagging this.
So far we are not aiming to move to the newest version of CSS selector because it requires PHP > 5.5.+ and we still need to have it compatible to PHP >= 5.4.

What I recommend you to do is:
* Checkout the master version of this component
* Change composer.json to set required version of the CSS Selector:
  ```
 "require": {
        "php": "^5.4 || ^7.0",
        "symfony/css-selector": "3.*",
        "facebook/graph-sdk": "~5.0",
        "apache/log4php": "2.3.0"
    }
```
* Run `composer update` then `composer install`

It will build a version compatible as you need.

Thanks for flagging this issue.

**Comment by ronaldgj** [comment]
For now I changed the composer.json of Laravel back to 2.8. I saw Laravel only uses it for 'tests'. For now I'm not using that so this is a temporary solution for me. I'll will try this soon and let you know if it worked!

Thank you for your respons!

**Comment by kamranata** [comment]
Hi @everton-rosario. I saw you added to your composer.json 
`"php": "^5.4 || ^5.6 || ^7",
"symfony/css-selector": "^2.8 || ^3.1 || ^4.1",`

But when I use `composer require facebook/facebook-instant-articles-sdk-php` composer uses another json file. `
        "php": "^5.4 || ^7.0",
        "symfony/css-selector": "^2.8 || ^3.0",`

Can you fix this?

**Comment by everton-rosario** [comment]
So you're mentioning a conflict with the symfony/css-selector. Can you propose a PR so I can understand better what you are proposing?

Thanks for reporting it.
