### ISSUE TITLE
WYSIWYG Instant Articles transformer

### ISSUE THREAD

**Issue by YOzaz** [facebook/facebook-instant-articles-sdk-php#26]
I have a proposal. In general, it's a great package, and it now has an implementation for WordPress as a plugin, which is fine. However, it may be interesting to create a package which would work as a wrapper for other systems as well.
It can be a universal package to translate ORM (or any data format) to Instant Articles format. The thing is, that most of the CMS systems actually do have database models (more or less), therefore have WYSIWYG editors installed - usually it's either CkEditor, either TinyMCE. If you'd make general translation code, taken from current [WordPress plugin](https://github.com/Automattic/facebook-instant-articles-wp) more abstract, it would be quite easy to adopt. E.g. people will be able to write native plugin to CkEditor itself.

**Comment by everton-rosario** [comment]
Hey @YOzaz, thanks for your feedback!
That would be a really nice to have feature over this engine, such as WYSIWYG editor.

Since it is a web translator tool (that works mainly with HTML documents) we have a roadmap to create a Chrome App that would be the WYSIWYG. Mainly for selectors and also an embed emulator of the InstantArticle view.

If you have some cycles to work on this we can help pushing it forward.
