### ISSUE TITLE
0

### ISSUE THREAD

**Issue by SamiEgy** [facebook/facebook-instant-articles-sdk-php#298]

**Comment by everton-rosario** [comment]
Hey @SamiEgy can you share the Instant Article markup you generated?
For you to generate InstantArticle, you gotta set it on the Element class InstantArticle.

Example code:
```
$instantArticle = InstantArticle::create()
                ->withCanonicalUrl('http://yourdomain/path/article.html')
                ->enableRTL()
...

$instantArticle->render();
```

Im closing it for now, since this is already covered by the SDK.

Let us know if you have any other problem or if this problem persists for you.
