### ISSUE TITLE
Preformatted HTML

### ISSUE THREAD

**Issue by codeman2872** [facebook/facebook-instant-articles-sdk-php#76]
If I have HTML that already is in IA format, how do I use the API to submit it?

**Comment by simonengelhardt** [comment]
@codeman2872 This use case is not currently covered by the API client included in the SDK, since that is designed to work with an instance of `Facebook\InstantArticles\Elements\InstantArticle` created with the DSL (optionally using `Facebook\InstantArticles\Transformer\Transformer` for markup transformation).

You can submit HTML directly to the API by following the instructions in the [API documentation](https://developers.facebook.com/docs/instant-articles/api). Since this API is a standard Facebook Graph API, you can choose to use the [Facebook SDK for PHP](https://github.com/facebook/facebook-php-sdk-v4) for this.

It may be helpful to see how this is [implemented here](https://github.com/facebook/facebook-instant-articles-sdk-php/blob/master/src/Facebook/InstantArticles/Client/Client.php#L94) (notice the `html_source` parameter).
