### ISSUE TITLE
Insufficient Transformer Documentation 

### ISSUE THREAD

**Issue by alexdelgado** [facebook/facebook-instant-articles-sdk-php#79]
I've been working with the "Instant Articles for WP" plugin which uses this library and I can't quite figure out how the transformer rules work, or how to create a new one, and the Quick Start Guide wasn't much help. It sort've just says, here are some things, they need these parameters, have fun. The code itself also doesn't have any docblocks so I can't wrap my head around what's actually going on and since everything is being autoloaded it's even harder to track. Please add some documentation so us non-facebook geniuses can work with this SDK.

FWIW I also created a ticket on the plugin support page: https://wordpress.org/support/topic/insufficient-transformer-documentation?replies=1

Thanks,
Alex

**Comment by demoive** [comment]
Hi @alexdelgado and we really appreciate the feedback regarding the documentation.

Understanding how Transformer Rules work and how to configure them is indeed complex, which is why I'm happy to say that in the past week we've extended our documentation with a section dedicated to giving clarity on the matter with supporting examples.

The [main description of this plugin](https://wordpress.org/plugins/fb-instant-articles/) now contains a high-level overview of the concept behind Transformer Rules. Additionally, supporting information has been added as [FAQs](https://wordpress.org/plugins/fb-instant-articles/faq/) and [screenshots](https://wordpress.org/plugins/fb-instant-articles/screenshots/).

To go deeper, our main documentation now contains a section dedicated to [Transformer Rules](https://github.com/facebook/facebook-instant-articles-sdk-php/blob/master/docs/QuickStart.md#transformer-rules) and how to customize them. We hope this would reduce any confusion and the time it takes to get configurations done.

I'll close out this issue but we welcome any feedback or possible improvements you can suggest. Feel free to reopen or submit a PR with recommendations!
